# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SURqVAdxmy05QH627X3mu3uNPiD2i-D0
"""

from tensorflow import keras
from keras import layers,Model
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Flatten, Dense, Activation,Lambda
from keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, concatenate, BatchNormalization, Reshape
from keras.models import Model
from keras import regularizers
from keras.layers import add
from tensorflow.keras.layers import Layer
from keras import backend as K

reg_weights = 1e-6

def bn_relu():
    def bn_relu_func(x):
        x = BatchNormalization()(x)
        x = Activation("relu")(x)
        return x

    return bn_relu_func

def res_conv(nb_filter, nb_row, nb_col, stride=(1, 1)):
    def _res_func(x):
        identity = x

        a = Conv2D(nb_filter, (nb_row, nb_col), strides=stride, padding='same', kernel_regularizer=regularizers.l2(reg_weights))(x)
        a = BatchNormalization()(a)
        a = Activation("relu")(a)
        a = Conv2D(nb_filter, (nb_row, nb_col), strides=stride, padding='same', kernel_regularizer=regularizers.l2(reg_weights))(a)
        y = BatchNormalization()(a)

        return add([identity, y])

    return _res_func

def dconv_bn_nolinear(nb_filter, nb_row, nb_col, stride=(2, 2), activation="relu"):
    def _dconv_bn(x):
        x = UpSampling2D(size=stride)(x)
        x = ReflectionPadding2D(padding=(int(nb_row/2), int(nb_col/2)))(x)
        x = Conv2D(nb_filter, (nb_row, nb_col), padding='valid', kernel_regularizer=regularizers.l2(reg_weights))(x)
        x = BatchNormalization()(x)
        x = Activation(activation)(x)
        return x

    return _dconv_bn

class ReflectionPadding2D(Layer):
    def __init__(self, padding=(1, 1), **kwargs):
        super().__init__(**kwargs)
        self.padding = padding

    def build(self, input_shape):
        pass  # No trainable weights, no need to build

    def call(self, x):
        paddings = tf.constant([[0, 0], [self.padding[1], self.padding[1]], [self.padding[0], self.padding[0]], [0, 0]])
        return tf.pad(x, paddings, mode='REFLECT')

    def compute_output_shape(self, input_shape):
        return (
            input_shape[0],
            input_shape[1] + 2 * self.padding[0] if input_shape[1] is not None else None,
            input_shape[2] + 2 * self.padding[1] if input_shape[2] is not None else None,
            input_shape[3]
        )

    def get_config(self):
        config = super().get_config()
        config.update({'padding': self.padding})
        return config


class UnPooling2D(UpSampling2D):
    def __init__(self, size=(2, 2)):
        super(UnPooling2D, self).__init__(size)

    def call(self, x, mask=None):
        shapes = x.get_shape().as_list()
        w = self.size[0] * shapes[1]
        h = self.size[1] * shapes[2]
        return tf.image.resize_nearest_neighbor(x, (w, h))


class InstanceNormalize(Layer):
    def __init__(self, **kwargs):
        super(InstanceNormalize, self).__init__(**kwargs)
        self.epsilon = 1e-3

    def call(self, x, mask=None):
        mean, var = tf.nn.moments(x, [1, 2], keep_dims=True)
        return tf.div(tf.subtract(x, mean), tf.sqrt(tf.add(var, self.epsilon)))

    def compute_output_shape(self, input_shape):
        return input_shape


def create_vae(input_size=(128, 128, 2),output_size = 2):
    # Encoder
    inputs = Input(shape = input_size, name = 'image')

    enc1_conv = Conv2D(16, (3, 3), strides = (2,2), padding='same', kernel_regularizer=regularizers.l2(reg_weights))(inputs)
    enc1_bn_relu = bn_relu()(enc1_conv)

    enc2_conv = Conv2D(32, (3, 3), strides=(1, 1), padding='same', kernel_regularizer=regularizers.l2(reg_weights))(enc1_bn_relu)
    enc2_bn_relu = bn_relu()(enc2_conv)

    enc3_conv = Conv2D(64, (3, 3), strides=(2, 2), padding='same', kernel_regularizer=regularizers.l2(reg_weights))(enc2_bn_relu)
    enc3_bn_relu = bn_relu()(enc3_conv)

    enc4_conv = Conv2D(64, (3, 3), strides=(1, 1), padding='same', kernel_regularizer=regularizers.l2(reg_weights))(enc3_bn_relu)
    enc4_bn_relu = bn_relu()(enc4_conv)

    enc5_conv = Conv2D(128, (3, 3), strides=(2, 2), padding='same', kernel_regularizer=regularizers.l2(reg_weights))(enc4_bn_relu)
    enc5_bn_relu = bn_relu()(enc5_conv)

    enc6_conv = Conv2D(128, (3, 3), strides=(1, 1), padding='same', kernel_regularizer=regularizers.l2(reg_weights))(enc5_bn_relu)
    enc6_bn_relu = bn_relu()(enc6_conv)

    x0 = res_conv(128, 3, 3)(enc6_bn_relu)
    x1 = res_conv(128, 3, 3)(x0)
    x2 = res_conv(128, 3, 3)(x1)
    x3 = res_conv(128, 3, 3)(x2)
    x4 = res_conv(128, 3, 3)(x3)
    x5 = res_conv(128, 3, 3)(x4)
    x6 = res_conv(128, 3, 3)(x5)

    merge6 = concatenate([enc6_bn_relu, x6], axis=3)
    dec6 = dconv_bn_nolinear(128, 3, 3, stride=(1, 1))(merge6)
    merge5 = concatenate([enc5_bn_relu, dec6], axis=3)
    dec5 = dconv_bn_nolinear(128, 3, 3, stride=(2, 2))(merge5)
    merge4 = concatenate([enc4_bn_relu, dec5], axis=3)
    dec4 = dconv_bn_nolinear(64, 3, 3, stride=(1, 1))(merge4)
    merge3 = concatenate([enc3_bn_relu, dec4], axis=3)
    dec3 = dconv_bn_nolinear(64, 3, 3, stride=(2, 2))(merge3)
    merge2 = concatenate([enc2_bn_relu, dec3], axis=3)
    dec2 = dconv_bn_nolinear(32, 3, 3, stride=(1, 1))(merge2)
    merge1 = concatenate([enc1_bn_relu, dec2], axis=3)
    dec1 = dconv_bn_nolinear(16, 3, 3, stride=(2, 2))(merge1)

    # Output layer
    output = Conv2D(1, (3, 3), padding='same', activation='linear')(dec1)
    flatten = Flatten()(output)
    output_scalar = Dense(output_size)(flatten)

    # Full net
    vae_model = Model(inputs=inputs, outputs=output_scalar)
    return vae_model